// <auto-generated />
using System;
using CustomPcStoreApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomPcStoreApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CustomPcStoreApp.Models.AssemblyComponent", b =>
                {
                    b.Property<int>("AssemblyTaskId")
                        .HasColumnType("int")
                        .HasColumnName("сборка_id");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int")
                        .HasColumnName("компонент_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("количество");

                    b.HasKey("AssemblyTaskId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("компоненты_в_сборке", (string)null);
                });

            modelBuilder.Entity("CustomPcStoreApp.Models.AssemblyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("сборка_id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата_завершения");

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("название_конфигурации");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("сотрудник_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("заказ_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("дата_начала");

                    b.Property<string>("StatusString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("статус");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusString")
                        .HasDatabaseName("idx_сборочные_статус");

                    b.ToTable("сборочные_задания", t =>
                        {
                            t.HasCheckConstraint("CK_сборочные_статус", "статус IN ('ожидает', 'в_сборке', 'готово')");
                        });
                });

            // Остальные сущности будут добавлены аналогично...
            // Для краткости показываю только основную структуру

#pragma warning restore 612, 618
        }
    }
}